<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Laki-laki_jenis_kelamin</name>
   <tag></tag>
   <elementGuidId>dd7c0300-db31-4ba4-95f1-bb2ee222a85b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='optionsRadiosLaki']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#optionsRadiosLaki</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f792187-bbca-481d-a37b-650043c8c070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7454b247-7c2a-49ea-b011-451bda8354e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jenis_kelamin</value>
      <webElementGuid>f1411a92-a8d1-4817-8510-a0ca52ad9329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optionsRadiosLaki</value>
      <webElementGuid>cd7b0d31-0cb7-4844-bd2a-a84d932a1db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>18a83f2c-457c-4668-ab57-f573794aab47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optionsRadiosLaki&quot;)</value>
      <webElementGuid>15818737-63f8-4fa1-babc-bd198f22d066</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='optionsRadiosLaki']</value>
      <webElementGuid>3640b164-6712-410c-8e9a-bac53f05d59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div[11]/div/label/input</value>
      <webElementGuid>8d8ea557-50fd-4855-ab27-8b85958ada8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/label/input</value>
      <webElementGuid>94f2f449-4a7e-4b70-ab05-43e90db48c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'jenis_kelamin' and @id = 'optionsRadiosLaki']</value>
      <webElementGuid>18b013ee-4ba5-430f-be8e-65b332162c79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
