<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID User_id_user</name>
   <tag></tag>
   <elementGuidId>a11310b8-6f40-4146-9d20-949a4cc7f3c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='id_user']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;id_user&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>883e64f5-e9c4-4333-ae30-3f612f1ee2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8035c9ca-3a89-439e-8d21-6c33de629d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d77249cf-abae-411a-b43b-8cc6a283631c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id_user</value>
      <webElementGuid>d40138f1-774d-481d-ad3f-03a6f4d8608c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ID User</value>
      <webElementGuid>86b6ab0c-33b5-4d75-82c6-d633e2594bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;section&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10&quot;]/form[1]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-5&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>f049c6b1-5203-4458-a269-508b0b7dc635</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='id_user']</value>
      <webElementGuid>52f1817b-2b13-4752-a4ed-9063d62644cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/div[2]/div/div/div/form/div/div[2]/input</value>
      <webElementGuid>255143f4-323f-4e84-a275-fdbd0e0cb875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>103d7e24-d62b-4dfd-8445-7c222465ed75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'id_user' and @placeholder = 'ID User']</value>
      <webElementGuid>997c046f-26e2-4c69-ab53-700d5fd962f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
