<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_KabupatenKABUPATEN BANTULKABUPATEN G_999db8</name>
   <tag></tag>
   <elementGuidId>d841200e-708f-430d-927c-3d5bd1d4c3a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Kab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Kab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>20bed77f-62ae-4dd5-98e1-dc85e65894b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>32c405c0-85d5-45be-86bc-81b892ec66c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Kab</value>
      <webElementGuid>64803a5e-7916-49ec-a6b8-d5aadd9621de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kabupaten</value>
      <webElementGuid>0f2f1b5c-b017-4123-8a6d-50b24f27d6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KabupatenKABUPATEN BANTULKABUPATEN GUNUNG KIDULKABUPATEN KULON PROGOKABUPATEN SLEMANKOTA YOGYAKARTA</value>
      <webElementGuid>50cec0f9-7528-4a60-8869-67df548d549d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kab&quot;)</value>
      <webElementGuid>3abba949-936d-45c7-8d5f-f68ff3f5cca0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Kab']</value>
      <webElementGuid>472e9931-3045-41c4-af26-ef6fb12674ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div/div/select</value>
      <webElementGuid>eb2120a8-5621-45a9-a140-4b8ee4145e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kabupaten *'])[1]/following::select[1]</value>
      <webElementGuid>a28c991f-f800-4b31-b4d8-f8f1246577ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provinsi *'])[1]/following::select[2]</value>
      <webElementGuid>83f8f6d5-6d90-4b74-848c-2fa6d2e6228a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan *'])[1]/preceding::select[1]</value>
      <webElementGuid>3463c5d7-fbe5-4d27-8f37-0f497b1900d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa / Kelurahan *'])[1]/preceding::select[2]</value>
      <webElementGuid>10b41986-4e39-463b-9bb0-686a9cf66f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/select</value>
      <webElementGuid>ca1ede00-1080-495e-aadf-1a0e7317051c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Kab' and @name = 'Kabupaten' and (text() = 'KabupatenKABUPATEN BANTULKABUPATEN GUNUNG KIDULKABUPATEN KULON PROGOKABUPATEN SLEMANKOTA YOGYAKARTA' or . = 'KabupatenKABUPATEN BANTULKABUPATEN GUNUNG KIDULKABUPATEN KULON PROGOKABUPATEN SLEMANKOTA YOGYAKARTA')]</value>
      <webElementGuid>da75f1b2-2d22-421c-9ef4-d1c18852cd00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
