<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_KecamatanSRANDAKANSANDENKRETEKPUNDON_96a685</name>
   <tag></tag>
   <elementGuidId>86171b0f-5051-4a2d-96e8-ce91db9d73a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Kec']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Kec</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1da660c4-5f35-4b09-b14b-5abb3694f46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>434f34be-a0f0-4fc4-8081-53d22abe8fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Kec</value>
      <webElementGuid>461ebbb3-b84c-4af9-a1f4-bbe87426065a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kecamatan</value>
      <webElementGuid>5c928bf9-f796-48b2-a8dd-589e2d635ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KecamatanSRANDAKANSANDENKRETEKPUNDONGBAMBANG LIPUROPANDAKBANTULJETISIMOGIRIDLINGOPLERETPIYUNGANBANGUNTAPANSEWONKASIHANPAJANGANSEDAYU</value>
      <webElementGuid>f77e5246-2cf0-439e-a3db-c71ee6daf535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kec&quot;)</value>
      <webElementGuid>8ec9bc11-160a-4f9a-b8f6-1815d6384d07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Kec']</value>
      <webElementGuid>5668ee6d-56b1-4783-9a9c-c667e2682383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div/div[2]/select</value>
      <webElementGuid>406d470c-26fa-4389-a4fc-c8ed26bc0133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan *'])[1]/following::select[1]</value>
      <webElementGuid>d8a956b2-ee5e-42a3-be91-9dd7e4da413e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kabupaten *'])[1]/following::select[2]</value>
      <webElementGuid>f398fdac-e315-4ba1-a433-e9879391c823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa / Kelurahan *'])[1]/preceding::select[1]</value>
      <webElementGuid>0514863e-c21a-4118-a762-89f83e907f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon *'])[1]/preceding::select[2]</value>
      <webElementGuid>6a53c2d6-3782-4c6f-a745-669d8c2d88cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>41c197a7-a310-485e-8847-3c97e7cf9376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Kec' and @name = 'Kecamatan' and (text() = 'KecamatanSRANDAKANSANDENKRETEKPUNDONGBAMBANG LIPUROPANDAKBANTULJETISIMOGIRIDLINGOPLERETPIYUNGANBANGUNTAPANSEWONKASIHANPAJANGANSEDAYU' or . = 'KecamatanSRANDAKANSANDENKRETEKPUNDONGBAMBANG LIPUROPANDAKBANTULJETISIMOGIRIDLINGOPLERETPIYUNGANBANGUNTAPANSEWONKASIHANPAJANGANSEDAYU')]</value>
      <webElementGuid>098ad05d-ab63-4f63-98d8-7ce97bed5ec0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
