<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Desa  KelurahanGADINGHARJOGADINGSARI_6dbf1c</name>
   <tag></tag>
   <elementGuidId>92e39082-bbfb-44b2-98c3-eb9cee46bbab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Desa']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Desa</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>79b902e0-bf16-4d9f-8996-427b03bae59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>46ec823e-449e-4762-ac87-3618405aa6fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Desa</value>
      <webElementGuid>42006858-6fd9-4b56-bda2-e5912c37e2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Desa_Kelurahan</value>
      <webElementGuid>e645c440-208d-4709-af34-53925bdfd2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Desa / KelurahanGADINGHARJOGADINGSARIMURTIGADINGSRIGADING</value>
      <webElementGuid>37fe7884-aac9-4b79-9b0a-8e97b3dc8109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Desa&quot;)</value>
      <webElementGuid>90726f48-eb57-47ef-b6a7-ad033c1ff1a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Desa']</value>
      <webElementGuid>ed453aa9-e593-409c-a08f-f305013f5e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div/div[3]/select</value>
      <webElementGuid>605884e5-ea80-4e45-aefc-99630834853c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa / Kelurahan *'])[1]/following::select[1]</value>
      <webElementGuid>841968ac-29be-4d21-a37f-5bf6fc0459f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan *'])[1]/following::select[2]</value>
      <webElementGuid>766bfc74-f586-4b62-83d1-5ce0d5f9f27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon *'])[1]/preceding::select[1]</value>
      <webElementGuid>da523b12-a6fe-490b-9216-676ef711898a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendidikan Terakhir'])[1]/preceding::select[1]</value>
      <webElementGuid>c5879b79-3c8a-4b81-9196-4b4d12172fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[3]/select</value>
      <webElementGuid>a5413ca0-a8ff-4e94-95d6-e0ed1c2060f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Desa' and @name = 'Desa_Kelurahan' and (text() = 'Desa / KelurahanGADINGHARJOGADINGSARIMURTIGADINGSRIGADING' or . = 'Desa / KelurahanGADINGHARJOGADINGSARIMURTIGADINGSRIGADING')]</value>
      <webElementGuid>b0c37e26-09de-44cd-9d96-79939bf300da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
