<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Islam                               _f363b0</name>
   <tag></tag>
   <elementGuidId>8b412808-1e59-41d0-a0b3-2f73723d06ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='agama']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;agama&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a449278b-ad90-47b0-aa69-d00cd52a7633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1500672b-f773-40d3-995f-4cf7dd960228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>agama</value>
      <webElementGuid>da6a8b1e-45a9-4ca6-a859-7c28357d5f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Islam
                                    Hindu
                                    Katolik
                                    Kristen
                                    Budha
                                    Konghucu
                                </value>
      <webElementGuid>83dd860b-a53c-4fc5-964f-b0fe06f99f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demoForm&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>7bcb86a1-19b6-4a8d-9aef-95349c02af77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='agama']</value>
      <webElementGuid>ff3ad4b5-bb6f-4e83-b165-61b43061073e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div[8]/select</value>
      <webElementGuid>7f593507-6874-4a68-bdcb-314d848afffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agama *'])[1]/following::select[1]</value>
      <webElementGuid>f0e6c0ae-4bdb-4e1b-b83e-a6f980c44f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email *'])[1]/following::select[1]</value>
      <webElementGuid>55d556cc-1273-46fb-84c0-92b6d1beaa45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi Keahlian *'])[1]/preceding::select[1]</value>
      <webElementGuid>7fcbd86a-4a69-458d-ab14-dd8a3f8e7883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Petani *'])[1]/preceding::select[1]</value>
      <webElementGuid>4c0aeeac-9028-4c72-b021-97befbe0ad93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/select</value>
      <webElementGuid>aefbea0f-3ab2-4e19-beac-cce3b7eb0918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'agama' and (text() = '
                                    Islam
                                    Hindu
                                    Katolik
                                    Kristen
                                    Budha
                                    Konghucu
                                ' or . = '
                                    Islam
                                    Hindu
                                    Katolik
                                    Kristen
                                    Budha
                                    Konghucu
                                ')]</value>
      <webElementGuid>676805fe-5b26-4c50-9065-3d18cc190a15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
