<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SD                                  _d31312</name>
   <tag></tag>
   <elementGuidId>ed640c8d-b56a-4140-af41-1bd5643f1ec2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='pendidikan_terakhir']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;pendidikan_terakhir&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>75967ec1-fac8-47e7-bce1-4b08d782ed7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c3faae5b-5add-456f-abab-2360ba5c4746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pendidikan_terakhir</value>
      <webElementGuid>a1bed4de-76d3-4063-a8a0-bbe788ea10fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    SD
                                    SMP
                                    SMA
                                    D1
                                    D2
                                    D3
                                    S1
                                    S2
                                    S3
                                </value>
      <webElementGuid>eb15ab4e-8eb9-4654-abb4-3b17f0ed5779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demoForm&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>9238f450-f76f-47fd-a225-8dbc084de775</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='pendidikan_terakhir']</value>
      <webElementGuid>871ed885-78f4-43df-85db-0da309362229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div[3]/select</value>
      <webElementGuid>865c6c13-c44d-44d7-b947-ebcf09c9246e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendidikan Terakhir'])[1]/following::select[1]</value>
      <webElementGuid>a38ef4f5-9a08-4580-bfd7-9ebe2f096255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon *'])[1]/following::select[1]</value>
      <webElementGuid>f2f67f25-be1d-4810-8c16-71758eac6999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Lahan *'])[1]/preceding::select[1]</value>
      <webElementGuid>84ee9b83-979a-4b21-b041-3ca17ad0aa61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Tanggungan *'])[1]/preceding::select[1]</value>
      <webElementGuid>5975743e-5171-4dff-a871-bd4be888dc71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>a1fff949-e42e-4eab-b30a-8b9c88214a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'pendidikan_terakhir' and (text() = '
                                    SD
                                    SMP
                                    SMA
                                    D1
                                    D2
                                    D3
                                    S1
                                    S2
                                    S3
                                ' or . = '
                                    SD
                                    SMP
                                    SMA
                                    D1
                                    D2
                                    D3
                                    S1
                                    S2
                                    S3
                                ')]</value>
      <webElementGuid>51acdb3c-2122-45a0-94dc-0ab936ed8c39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
